name: 'Common Setup'
description: 'Install Just and Go'

inputs:
  go-version:
    description: 'Go version to install (defaults to version from go.mod)'
    required: false

runs:
  using: "composite"
  steps:
    - name: Install Just
      uses: extractions/setup-just@v3
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: Setup Go
      uses: actions/setup-go@v6
      with:
        go-version: ${{ inputs.go-version }}
        go-version-file: ${{ inputs.go-version && '' || 'go.mod' }}
