linters:
  enable:
    - bodyclose
    - errorlint
    - goconst
    - gocritic
    - gofumpt
    - gosec
    - misspell
    - mnd
    - musttag
    - testpackage
    - unparam
    - usestdlibvars
linters-settings:
  gofumpt:
    module-path: "pkgstats-cli"
