linters:
  enable:
    - bodyclose
    - dupl
    - errcheck
    - errorlint
    - goconst
    - gocritic
    - gocyclo
    - gofumpt
    - gosec
    - misspell
    - mnd
    - musttag
    - perfsprint
    - testpackage
    - unparam
    - usestdlibvars
linters-settings:
  gofumpt:
    module-path: "pkgstats-cli"
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - perfsprint
