version: "2"
run:
  tests: true
linters:
  enable:
    - bodyclose
    - dupl
    - errorlint
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - govet
    - misspell
    - mnd
    - musttag
    - perfsprint
    - staticcheck
    - testpackage
    - unparam
    - usestdlibvars
  exclusions:
    generated: lax
    rules:
      - path: _test\.go$
        linters:
          - perfsprint
          - gosec
      - path: _test\.go$
        linters:
          - gosec
  settings:
    errcheck:
      exclude-functions:
        - (*os.File).Close
        - (*text/tabwriter.Writer).Flush
        - (io.Closer).Close
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln
    gosec:
      excludes:
        - G104
formatters:
  enable:
    - gofumpt
  settings:
    gofumpt:
      module-path: pkgstats-cli
