version: "2"
linters:
  enable:
    - bodyclose
    - dupl
    - errorlint
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - govet
    - misspell
    - mnd
    - musttag
    - perfsprint
    - staticcheck
    - testpackage
    - unparam
    - usestdlibvars
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - perfsprint
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofumpt
  settings:
    gofumpt:
      module-path: pkgstats-cli
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
