name: test

on:
  push:
  schedule:
    - cron: '0 1 */1 * *'

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Run Common Setup
        uses: ./.github/actions/setup
      - name: golangci-lint
        uses: golangci/golangci-lint-action@82606bf257cbaff209d206a39f5134f0cfbfd2ee # v9.2.1
        with:
          verify: false
      - run: just lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Run Common Setup
        uses: ./.github/actions/setup
      - run: just test

  test-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Run Common Setup
        uses: ./.github/actions/setup
      - run: just test-integration

  test-cross-platform:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: ['aarch64', 'arm', 'i686', 'loongarch64', 'riscv64', 'x86_64']
        test: ['test', 'build', 'test-cpu-detection', 'test-os-detection']
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Run Common Setup
        uses: ./.github/actions/setup
      - name: Install Qemu
        run: sudo apt-get update && sudo apt-get install -y qemu-user
      - name: ${{ matrix.test }} on ${{ matrix.arch }}
        run: just ${{ matrix.arch }} ${{ matrix.test }}
