name: test

on:
  push:
  schedule:
    - cron: '0 1 */1 * *'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Just
        uses: extractions/setup-just@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Cross
        uses: taiki-e/install-action@v2
        with:
          tool: cross
      - run: just check

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Just
        uses: extractions/setup-just@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Cross
        uses: taiki-e/install-action@v2
        with:
          tool: cross
      - run: just test

  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Just
        uses: extractions/setup-just@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Cross
        uses: taiki-e/install-action@v2
        with:
          tool: cross
      - run: just test-build
      - run: just build

  test-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Just
        uses: extractions/setup-just@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: just test-integration

  test-cross-platform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Just
        uses: extractions/setup-just@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Cross
        uses: taiki-e/install-action@v2
        with:
          tool: cross
      - name: Update APT
        run: sudo apt-get update
      - name: Install Qemu
        run: sudo apt-get install qemu-user
      - run: just test-cross-platform

  test-cpu-detection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Just
        uses: extractions/setup-just@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Cross
        uses: taiki-e/install-action@v2
        with:
          tool: cross
      - name: Update APT
        run: sudo apt-get update
      - name: Install Qemu
        run: sudo apt-get install qemu-user
      - run: just test-cpu-detection
