name: test

on:
  push:
  schedule:
    - cron: '0 1 */1 * *'

jobs:
  lint:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v5
          with:
            fetch-depth: 0
        - name: Install Just
          uses: extractions/setup-just@v3
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        - name: Setup Go
          uses: actions/setup-go@v6
          with:
            go-version: '1.24'
        - name: golangci-lint
          uses: golangci/golangci-lint-action@v8
          with:
            verify: false
        - run: just lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Install Just
        uses: extractions/setup-just@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.24'
      - run: just test

  test-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Install Just
        uses: extractions/setup-just@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: just test-integration

  test-cross-platform:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: ['aarch64', 'arm', 'i686', 'loongarch64', 'riscv64', 'x86_64']
        test: ['test', 'build', 'test-cpu-detection', 'test-os-detection']
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Install Just
        uses: extractions/setup-just@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.24'
      - name: Update APT
        run: sudo apt-get update
      - name: Install Qemu
        run: sudo apt-get install qemu-user
      - name: ${{ matrix.test }} on ${{ matrix.arch }}
        run: just ${{ matrix.arch }} ${{ matrix.test }}
