name: test

on:
  push:
  schedule:
    - cron: '0 1 */1 * *'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: make build
      - run: make test
