name: test

on:
  push:
  schedule:
    - cron: '0 1 */1 * *'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - run: make build
      - run: make test
      - run: make test-build

  test-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - run: make test-integration

  test-cross-platform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - run: sudo apt-get install -y qemu-user
      - run: make test-cross-platform
      - run: make test-cpu-detection
