name: test

on:
  push:
  schedule:
    - cron: '0 1 */1 * *'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: make build
      - run: make test

  test-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: make test-integration

  test-cross-platform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Qemu
        run: sudo apt-get install qemu-user
      - run: make test-cross-platform

  test-cpu-detection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Qemu
        run: sudo apt-get install qemu-user
      - run: make test-cpu-detection
