name: test

on:
  push:
  schedule:
    - cron: '0 1 */1 * *'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Just
        uses: extractions/setup-just@v1
      - run: just build
      - run: just test

  test-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Just
        uses: extractions/setup-just@v1
      - run: just test-integration

  test-cross-platform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Just
        uses: extractions/setup-just@v1
      - name: Install Qemu
        run: sudo apt-get install qemu-user
      - run: just test-cross-platform

  test-cpu-detection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Just
        uses: extractions/setup-just@v1
      - name: Install Qemu
        run: sudo apt-get install qemu-user
      - run: just test-cpu-detection
